"""Auditable NL2SQL product package."""

from .answer import ANSWER_SCHEMA_VERSION, AnswerCompositionError, compose_answer
from .database import (
    ColumnSchema,
    ForeignKeySchema,
    QueryExecutionError,
    QueryResult,
    QueryTimeoutError,
    ReadOnlyViolation,
    TableSchema,
    execute_read_only,
    read_schema,
    validate_read_only_statement,
)
from .evidence import (
    EVIDENCE_CANONICALIZATION,
    EVIDENCE_SCHEMA_VERSION,
    EvidenceBindingError,
    ResultValidationError,
    bind_evidence,
    validate_result,
    verify_evidence,
)
from .provider import (
    DEEPSEEK_CHAT_COMPLETIONS_URL,
    DEEPSEEK_DEFAULT_MODEL,
    PROVIDER_RECEIPT_SCHEMA_VERSION,
    DeepSeekHttpTransport,
    DeepSeekSqlGenerator,
    ProviderConfigurationError,
    ProviderDecisionError,
    ProviderDisabledError,
    ProviderResponseError,
    ProviderTransportError,
    SqlGenerationError,
    SqlGenerationResult,
)
from .workflow import (
    CANONICAL_QUESTION,
    CANONICAL_SQL,
    DEFAULT_APPROVAL_ROW_LIMIT,
    DEFAULT_RESULT_ROW_LIMIT,
    DuplicateRunError,
    InvalidApprovalDecisionError,
    RunNotFoundError,
    StaticSqlGenerator,
    UnsupportedQuestionError,
    WorkflowRunner,
)

__all__ = [
    "ANSWER_SCHEMA_VERSION",
    "AnswerCompositionError",
    "compose_answer",
    "ColumnSchema",
    "ForeignKeySchema",
    "QueryExecutionError",
    "QueryResult",
    "QueryTimeoutError",
    "ReadOnlyViolation",
    "TableSchema",
    "execute_read_only",
    "read_schema",
    "validate_read_only_statement",
    "EVIDENCE_CANONICALIZATION",
    "EVIDENCE_SCHEMA_VERSION",
    "EvidenceBindingError",
    "ResultValidationError",
    "bind_evidence",
    "validate_result",
    "verify_evidence",
    "DEEPSEEK_CHAT_COMPLETIONS_URL",
    "DEEPSEEK_DEFAULT_MODEL",
    "PROVIDER_RECEIPT_SCHEMA_VERSION",
    "DeepSeekHttpTransport",
    "DeepSeekSqlGenerator",
    "ProviderConfigurationError",
    "ProviderDecisionError",
    "ProviderDisabledError",
    "ProviderResponseError",
    "ProviderTransportError",
    "SqlGenerationError",
    "SqlGenerationResult",
    "CANONICAL_QUESTION",
    "CANONICAL_SQL",
    "DEFAULT_APPROVAL_ROW_LIMIT",
    "DEFAULT_RESULT_ROW_LIMIT",
    "DuplicateRunError",
    "InvalidApprovalDecisionError",
    "RunNotFoundError",
    "StaticSqlGenerator",
    "UnsupportedQuestionError",
    "WorkflowRunner",
]
