"""Auditable NL2SQL product package."""

from .database import (
    ColumnSchema,
    ForeignKeySchema,
    QueryExecutionError,
    QueryResult,
    QueryTimeoutError,
    ReadOnlyViolation,
    TableSchema,
    execute_read_only,
    read_schema,
    validate_read_only_statement,
)
from .evidence import (
    EVIDENCE_CANONICALIZATION,
    EVIDENCE_SCHEMA_VERSION,
    EvidenceBindingError,
    ResultValidationError,
    bind_evidence,
    validate_result,
    verify_evidence,
)
from .workflow import (
    CANONICAL_QUESTION,
    CANONICAL_SQL,
    DEFAULT_APPROVAL_ROW_LIMIT,
    DEFAULT_RESULT_ROW_LIMIT,
    DuplicateRunError,
    InvalidApprovalDecisionError,
    RunNotFoundError,
    StaticSqlGenerator,
    UnsupportedQuestionError,
    WorkflowRunner,
)

__all__ = [
    "ColumnSchema",
    "ForeignKeySchema",
    "QueryExecutionError",
    "QueryResult",
    "QueryTimeoutError",
    "ReadOnlyViolation",
    "TableSchema",
    "execute_read_only",
    "read_schema",
    "validate_read_only_statement",
    "EVIDENCE_CANONICALIZATION",
    "EVIDENCE_SCHEMA_VERSION",
    "EvidenceBindingError",
    "ResultValidationError",
    "bind_evidence",
    "validate_result",
    "verify_evidence",
    "CANONICAL_QUESTION",
    "CANONICAL_SQL",
    "DEFAULT_APPROVAL_ROW_LIMIT",
    "DEFAULT_RESULT_ROW_LIMIT",
    "DuplicateRunError",
    "InvalidApprovalDecisionError",
    "RunNotFoundError",
    "StaticSqlGenerator",
    "UnsupportedQuestionError",
    "WorkflowRunner",
]
